name: build-it
on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-it:
    name: build-it
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    
    - name: test em
      run: | 
        npm install
        npm install -g --save-dev shadow-cljs
        shadow-cljs compile test

    - name: build em
      run: |
        shadow-cljs release frontend
        sha256sum public/js/main.js > target/dda-masto-embed.js.sha256
        sha512sum public/js/main.js > target/dda-masto-embed.js.sha512

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload masto-embed.js
      id: upload-masto-embed-js
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: public/js/main.js
        asset_name: dda-masto-embed.js
        asset_content_type: application/json

    - name: Upload masto-embed.js.sha256
      id: upload-masto-embed-js-sha256
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/dda-masto-embed.js.sha256
        asset_name: dda-masto-embed.js.sha256
        asset_content_type: application/json

    - name: Upload masto-embed.js.sha512
      id: upload-masto-embed-js-sha512
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/dda-masto-embed.js.sha512
        asset_name: dda-masto-embed.js.sha512
        asset_content_type: application/json

    - name: upload to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        mkdir -p target/npm-build/dda-masto-embed     
        cp public/js/main.js target/npm-build/dda-masto-embed/dda-masto-embed.js
        cp target/dda-masto-embed.js.sha256 target/npm-build/dda-masto-embed/
        cp target/dda-masto-embed.js.sha512 target/npm-build/dda-masto-embed/
        cp package.json target/npm-build/dda-masto-embed/
        cp README.md target/npm-build/dda-masto-embed/
        cp -r doc target/npm-build/dda-masto-embed/
        cp LICENSE target/npm-build/dda-masto-embed/
        npm publish target/npm-build --access public
